server:
  port: 8081

spring:
  application:
    name: petri-net-api
  
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/pickndrop_db
    username: postgres
    password: jeff1234
    pool:
      initial-size: 5
      max-size: 10
  
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  level:
    com.yowyob.petrinet: DEBUG
    org.springframework.data.r2dbc: DEBUG
